Add exam support for assessment
ls1intum/Themis pull request #113
Opened 2023-02-07 18:06 UTC by botrufus

- Course View:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/64660684/217328868-1c8f705a-6caf-46ff-b87f-3fd413c8ab01.png">
- Exam exercises view:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/64660684/217328946-dc77b93b-513b-4822-805b-e3c6d6ae7acb.png">

2023-02-07 18:08 UTC, AlexExcellence commented on Themis/Views/Exams/ExamListView.swift
> +                    Text(exam.title)
```suggestion
                    Text(exam.title)
                        .font(.title2)
                        .fontWeight(.medium)
```

2023-02-07 19:42 UTC, crustypluto19 requested changes, later dismissed
Code looks great!

I find it kinda weird that from course view when clicking on an exam, we go to this intermediate page where there is a list of current exams (here written as current exercises, I think it should be "current exams" instead, not sure tho).

![simulator_screenshot_5DCB742F-AFC7-408C-8CA7-9202EA090830](https://user-images.githubusercontent.com/24537483/217347999-cd947ac9-5549-473e-9bee-879bc056a2e3.png)

Is it the case that there might be multiple exercises for a given exam, hence this intermediate view? If that is the case I think it should be made clearer, maybe having a navigation title for this view. It would also make it consistent with other the Exercise View.

2023-02-07 19:42 UTC, crustypluto19 commented on Themis/Models/Exercise.swift
> +    var releaseDate: String?
Why were these attributes changed from `let` to `var`?

2023-02-07 21:11 UTC, huber-florian commented on Themis/Views/Exercises/ExerciseSections.swift
> +struct ExerciseSections: View {
I don't see a reason , why to change the name. If we change it, I would at least prefer that it is called ExerciseSectionsView.

2023-02-07 21:11 UTC, huber-florian commented on Themis/Views/Exercises/ExerciseSections.swift
>  struct ExercisesListView_Previews: PreviewProvider {
If you change the name, then change it here as well.

2023-02-07 21:26 UTC, huber-florian commented
Cannot click on Start Assessment resp. appear when I click on it even if I am an instructor.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/116847304/217369203-b77258ba-ad9f-4c35-85ba-c26104a4f352.png">

2023-02-07 21:36 UTC, huber-florian commented
Why don't you add the Exam in the Course View in the same way, as a course, and if you select the exam there are only the exam exercises shown. In that case the flow would be the same as with any other course. In my opinion that would be more intuitive and furthermore you would not have to abuse all views that much.

2023-02-07 23:04 UTC, crustypluto19 commented
> Cannot click on Start Assessment resp. appear when I click on it even if I am an instructor.
> 
> <img alt="image" width="808" src="https://user-images.githubusercontent.com/116847304/217369203-b77258ba-ad9f-4c35-85ba-c26104a4f352.png">

After some investigating, I found get this error message: 
`{"type":"https://www.jhipster.tech/problem/problem-with-message","title":"Forbidden","status":403,"detail":"The due date of exercise 'Themis-Exam' has not been reached yet.","path":"/api/exercises/5617/programming-submission-without-assessment","message":"error.http.403"}`

The due date has simply not been reached yet, and the fault does not lie on the client side.

2023-02-09 02:13 UTC, botrufus commented
![Simulator Screen Recording - iPad Air (5th generation) - 2023-02-09 at 03 09 06](https://user-images.githubusercontent.com/64660684/217699169-5e724876-00c8-49e6-af8a-45e43bdc0d87.gif)

- As discussed: changes to the UI
+ You can use the Exam Test3 to test the assessment mode without getting any errors (until the 11th of February at least)

2023-02-09 06:17 UTC, huber-florian requested changes
According to your video the second view still has no title and the section is called current exercises. Both some things we discussed yesterday that should be changed.

2023-02-09 09:54 UTC, botrufus commented
added a navigation title and removed the exercise sections view completely as the dates for all exercises will be the same anyways

2023-02-09 10:02 UTC, pal03377 approved these changes
Code looks good, showing exams & opening exercises works. I think overall this PR improves the app as it is. There are some minor things I would want to be changed, see below.

Also, because I can only find one available submission currently, I didn't want to "waste" it by submitting, so I didn't test whether that works. Please test that with the submission we have before merging.

2023-02-09 10:02 UTC, pal03377 commented on Themis/Views/Exams/ExamListItem.swift
> +//
This file seems to be removed from the XCode project, but the file itself is still here. Please remove.

2023-02-09 10:02 UTC, pal03377 commented on Themis/Views/Exams/ExamListView.swift
> +    private let assessmentStartDate = ExamDateProperty(name: "Assessment", dateKeyPath: \.startDate)
If it's implicitly assumed that assessmentStartDate = exam date, I think we should only show the date once in the UI.

2023-02-09 10:02 UTC, pal03377 commented on Themis/Views/Courses/CourseView.swift
> +                        if let courseId = courseVM.shownCourse?.id {
I think this `if` should also include the condition that there is >= 1 exam so that it will not be empty (or will the section automatically be hidden in that case?)

2023-02-09 10:02 UTC, huber-florian approved these changes

2023-02-09 10:16 UTC, botrufus commented
> Also, because I can only find one available submission currently, I didn't want to "waste" it by submitting, so I didn't test whether that works. Please test that with the submission we have before merging.

It's exactly the same interface as with the other exercises, but sure I can do that

2023-02-09 10:20 UTC, botrufus commented on Themis/Views/Exams/ExamListView.swift
> +    private let assessmentStartDate = ExamDateProperty(name: "Assessment", dateKeyPath: \.startDate)
If the exam for some reason goes over several days, exam date will be different to assessmentStartDate. And especially if you're not familiar with the system you don't now that assessmentStartDate = exam date so its definitely not unnecessary information

2023-02-09 10:28 UTC, botrufus commented
>> Also, because I can only find one available submission currently, I didn't want to "waste" it by submitting, so I didn't test whether that works. Please test that with the submission we have before merging.

> It's exactly the same interface as with the other exercises, but sure I can do that

Works as expected

2023-02-09 10:32 UTC, merged