Problem statement webview
ls1intum/Themis pull request #153
Opened 2023-04-27 18:37 UTC by terlan98

### This is a copy of #152 excluding commits from other branches to make it easier to review.

Integrated the new problem statement component inside an `ArtemisWebView`.

The PR is complete, but shouldn't be merged until [Development: Provide standalone problem statement for external apps #6427](https://github.com/ls1intum/Artemis/pull/6427) is merged.

2023-05-13 09:28 UTC, terlan98 commented
I resolved the merge conflicts, but this PR should not be merged yet, since there's a problem with the new standalone problem statement component. It can't fetch exercises belonging to exams ☹️

2023-06-02 10:23 UTC, maximiliansoelch requested changes
Can we fix the display of UML Diagrams in the problem statement view of the exercise and a submission? 
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-06-02 at 12 17 11](https://github.com/ls1intum/Themis/assets/9954674/a8302d0a-c959-4746-a8a9-6b50d9dcf724)
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-06-02 at 12 18 49](https://github.com/ls1intum/Themis/assets/9954674/5deaecee-27f6-433d-877c-6e1f6043dbbb)

Further, can we cache the problem statement so we do not have to load it all the time?

https://github.com/ls1intum/Themis/assets/9954674/04ae672d-9a30-454e-89b9-875f9ba1a076

2023-06-02 10:23 UTC, maximiliansoelch commented on Themis/ViewModels/Authentication/PreviewAuthenticationViewModel.swift
>          self.password = password
What has this to do with the problem statement?

2023-06-02 10:23 UTC, maximiliansoelch commented on Themis/Views/Exercises/ProblemStatementView.swift
> +            self._request = State(wrappedValue: URLRequest(url: URL(string: "https://google.com")!))
Can we avoid this?

2023-06-02 16:41 UTC, terlan98 commented on Themis/ViewModels/Authentication/PreviewAuthenticationViewModel.swift
>          self.password = password
This change was needed to fix the `AuthenticatedPreview`, which is needed to preview the `ProblemStatementView`

2023-06-02 17:37 UTC, terlan98 commented on Themis/Views/Exercises/ProblemStatementView.swift
> +            self._request = State(wrappedValue: URLRequest(url: URL(string: "https://google.com")!))
Done

2023-06-04 10:23 UTC, terlan98 commented
The issue on the **first screenshot** was due to the ArtemisWebView not setting it's height correctly when the connection speed was slow. This [ArtemisCore PR](https://github.com/ls1intum/artemis-ios-core-modules/pull/8) will fix it.

---
The issue on the **second screenshot**, where the UML diagram is cut off horizontally, will be fixed with this [Artemis PR](https://github.com/ls1intum/Artemis/pull/6667)

---
**Regarding the caching-related question**: I've looked into several ways of implementing a cache (NSURLProtocol and WKURLSchemeHandler) but unfortunately WKWebView is very restricted and does not allow intercepting requests and responses to cache them. I also tried downloading the webpage content as a file and then loading it from the file for subsequent requests. This approach also did not lead to any significant loading speed improvements. 

So instead of implementing a cache, what I did in my latest commit was to prevent ProblemStatementView from being redrawn when the user interacts with the Picker. The page will still reload if the user hides the sidebar completely and reopens it.

2023-06-09 15:13 UTC, maximiliansoelch approved these changes
Tested locally, Problem statement view works as expected.
Code LGTM 👍

2023-06-09 15:13 UTC, merged