Add SwiftLint action file
ls1intum/Themis pull request #154
Opened 2023-04-27 19:38 UTC by terlan98

2023-04-28 10:37 UTC, maximiliansoelch commented
The gh action from norio-nomura is quite old. Can we use this fork instead: https://github.com/sinoru/actions-swiftlint

2023-04-28 10:38 UTC, maximiliansoelch requested changes

2023-04-28 10:38 UTC, maximiliansoelch commented on .github/workflows/swiftlint.yml
> +          args: --config swiftlint.yml --strict
We don't need four SwiftLint runs, just the one for changed files and our custom SwiftLint config file
```suggestion
```

2023-04-28 10:38 UTC, maximiliansoelch commented on .github/workflows/swiftlint.yml
> +          WORKING_DIRECTORY: Source
```suggestion
```

2023-04-28 10:38 UTC, maximiliansoelch commented on .github/workflows/swiftlint.yml
Please also change to the other gh action mentioned in my comment above

2023-04-28 15:59 UTC, terlan98 commented on .github/workflows/swiftlint.yml
The other gh action failed for some reason. I will try it again

2023-04-29 17:32 UTC, maximiliansoelch approved these changes

2023-04-29 17:34 UTC, merged