Core login integration
ls1intum/Themis pull request #157
Opened 2023-05-14 08:36 UTC by terlan98

2023-05-17 18:23 UTC, terlan98 commented
Changed base branch to `chore/refactor` to make reviewing easier. Please change back to `develop` while merging

2023-05-19 12:35 UTC, maximiliansoelch commented on Themis.xcodeproj/project.pbxproj
> +		65153F9C2A0F97F70020B6FE /* artemis-ios-core-modules */ = {isa = PBXFileReference; lastKnownFileType = wrapper; name = "artemis-ios-core-modules"; path = "../artemis-ios-core-modules"; sourceTree =
This shouldn't be here, right?

2023-05-19 12:38 UTC, maximiliansoelch requested changes
Code looks good 👍
However, locally the build fails for me, so I can't test + merge conflicts with develop.

2023-05-22 10:08 UTC, maximiliansoelch approved these changes
Now tested locally, login still works as expected after the changes 👍

2023-05-22 10:09 UTC, merged