CourseView Redesign
ls1intum/Themis pull request #159
Opened 2023-05-21 12:20 UTC by terlan98

2023-06-12 16:11 UTC, maximiliansoelch requested changes
I have a few questions and feedback:

Can you align the grey area with the labels on top as you did in your Figma mockup?
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-06-12 at 17 53 31](https://github.com/ls1intum/Themis/assets/9954674/99f6b4a7-1cc9-4860-8c5e-e4766ea2ced6)

The last cell has a divider at the bottom:
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-06-12 at 17 51 33](https://github.com/ls1intum/Themis/assets/9954674/2cb52d93-2d5c-4c82-8e40-db980ce75580)

2023-06-12 16:11 UTC, maximiliansoelch commented on Themis/Views/Exercises/ExerciseSection.swift
> +    private let releaseDate = ExerciseDateProperty(name: "Release", dateKeyPath: \.baseExercise.releaseDate)
May change the order according to the chronological appearance.

```suggestion
    private let releaseDate = ExerciseDateProperty(name: "Release", dateKeyPath: \.baseExercise.releaseDate)
    private let dueDate = ExerciseDateProperty(name: "Submission", dateKeyPath: \.baseExercise.dueDate)
    private let assessmentDueDate = ExerciseDateProperty(name: "Assessment", dateKeyPath: \.baseExercise.assessmentDueDate)
```

2023-06-12 16:11 UTC, maximiliansoelch commented on Themis/Views/Exams/ExamSection.swift
> +    private let assessmentStartDate = ExamDateProperty(name: "Assessment", dateKeyPath: \.startDate)
Are you sure that `\.startDate` should be also used for the `assessmentStartDate`?

2023-06-12 16:11 UTC, maximiliansoelch commented on Themis/Extensions/ExamExtension.swift
> +        if let publishResultsDate = self.publishResultsDate {
How do `assessmentDue` and `publishResultDate` correlate here?

2023-06-13 09:42 UTC, terlan98 commented on Themis/Extensions/ExamExtension.swift
> +        if let publishResultsDate = self.publishResultsDate {
The exam model does not have a property indicating when the assessment is due. That's why `publishResultDate` is used instead 🙂

2023-06-13 19:44 UTC, terlan98 commented on Themis/Views/Exams/ExamSection.swift
> +    private let assessmentStartDate = ExamDateProperty(name: "Assessment", dateKeyPath: \.startDate)
This is a mistake. Thanks for pointing out.

2023-06-14 08:13 UTC, maximiliansoelch approved these changes
Tested again locally, code looks good! 👍

2023-06-14 08:14 UTC, merged