`Programming exercise`: Enable viewing template and solution repositories
ls1intum/Themis pull request #162
Opened 2023-06-16 07:17 UTC by terlan98

This PR adds functionality to view the solution and template repositories while assessing a programming submission.

2023-06-30 14:58 UTC, maximiliansoelch requested changes
Tested locally. During assessment, switching between the different repos works as expected.
However, in the read-only mode, there seems to be an issue:

https://github.com/ls1intum/Themis/assets/9954674/a7d497a8-8c81-45e8-a34e-20a160349d5d

2023-07-03 12:39 UTC, terlan98 commented
Thanks for the review! This Artemis PR (https://github.com/ls1intum/Artemis/pull/6810) will fix the issue.

2023-07-05 12:28 UTC, terlan98 commented
The issue is now fixed 🙂

2023-07-06 12:36 UTC, maximiliansoelch approved these changes
Code looks good. Also tested locally and viewing the template/solution repos works as expected 👍

2023-07-06 12:36 UTC, maximiliansoelch commented on Themis/Views/Assessment/FiletreeSidebar/FiletreeSidebarView.swift
> +            Picker(selection: $repositorySelection) {
Not sure yet, if this is the optimal position for the picker. We should talk about some alternative placements

2023-07-06 12:37 UTC, merged