Modeling exercise support
ls1intum/Themis pull request #163
Opened 2023-07-07 07:50 UTC by terlan98

This PR adds support for assessing modeling exercises

The following features, in particular, are added for modeling exercises:
- **Starting** a new assessment
- Rendering UML models
- **Creating "inline" feedbacks** for model elements
- Creating **general feedbacks**
- **Deleting and editing** feedbacks
- **Canceling** an assessment
- **Saving** an assessment
- **Submitting** an assessment
- The aforementioned operations for modeling exercises in **exams**

What is NOT included in this PR:
-

2023-08-09 08:04 UTC, maximiliansoelch requested changes
Overall code looks good, I just left a few comments. Also quickly tested it locally and it seems to work as expected 👍

I have some comments that should be addressed either in this PR or a follow-up:

1. The attributes and methods should be grouped and not just added in a single rectangle:
<img width="131" alt="Screenshot 2023-08-09 at 16 48 59" src="https://github.com/ls1intum/Themis/assets/9954674/c7d2a8b6-0693-4655-affa-0cb76cf738b8">

2. The badges are very hard to read/recognize (especially the suggestion badge). We may need to increase the opacity of the badge's background: 
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-08-09 at 14 45 14](https://github.com/ls1intum/Themis/assets/9954674/c3101d8f-f791-448c-a985-ca5e4d94c3f3)

3. When I tap on a model element and then switch over to the "giving feedback" mode, the element is already marked:

https://github.com/ls1intum/Themis/assets/9954674/8711585c-3b98-4f10-91d4-b2b03ae3512a


4. Also, I noticed the problem statement has no padding for text and modeling exercises:

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-08-09 at 14 33 27](https://github.com/ls1intum/Themis/assets/9954674/1a659a32-1bc4-44e8-8e7b-f6c8706231cb)
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-08-09 at 14 32 58](https://github.com/ls1intum/Themis/assets/9954674/a9b95884-899a-485b-a82f-abd43ec47f19)
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-08-09 at 14 32 38](https://github.com/ls1intum/Themis/assets/9954674/7a83dd69-c03e-4f07-bee9-e5b25b3044a9)

2023-08-09 08:04 UTC, maximiliansoelch commented on Themis.xcodeproj/project.pbxproj
> +		65A49CF02A55B62E00F8B716 /* artemis-ios-core-modules */ = {isa = PBXFileReference; lastKnownFileType = wrapper; name = "artemis-ios-core-modules"; path = "../artemis-ios-core-modules"; sourceTree =
```suggestion
```
This shouldn't be here, right?

2023-08-09 08:04 UTC, maximiliansoelch commented on Themis/Views/Assessment/CorrectionSidebar/FeedbackListView.swift
> +    private var athenaHintBox: some View {
I would rename that variable to automaticFeedbackHintBox or something. Not everybody knows what Athena is.
```suggestion
    private var automaticFeedbackHintBox: some View {
```

2023-08-09 08:04 UTC, maximiliansoelch commented on Themis/ViewModels/Assessment/AssessmentViewModel.swift
> +
?

2023-08-10 19:06 UTC, terlan98 commented
Thanks! I addressed your comments 🙂

2023-08-21 09:34 UTC, maximiliansoelch approved these changes
Code looks good. Also tested it locally, and it worked as expected 👍

I have two minor enhancements for follow-up PRs:

1. If a class is abstract, the class name should be italic.
2. If an automatic suggestion for a class is present, only the header should be highlighted, but not the entire class, including attributes and methods.

Representation in Artemis:
![Screenshot 2023-08-21 at 10 49 55](https://github.com/ls1intum/Themis/assets/9954674/8e0bf0a7-df20-44bd-a676-9373fcacfbed)

Current state in Themis:
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-08-21 at 10 49 48](https://github.com/ls1intum/Themis/assets/9954674/ddab196d-ee5c-429d-b674-1b25b45b9a93)

2023-08-21 09:36 UTC, merged