`Modeling Exercise`: Add use case diagrams
ls1intum/Themis pull request #169
Opened 2023-08-02 17:05 UTC by terlan98

2023-09-06 21:33 UTC, maximiliansoelch requested changes
Code looks good in general 👍
Just left one small suggestion

2023-09-06 21:33 UTC, maximiliansoelch commented on Themis/Models/UML/UMLRelationshipType.swift
> +            return "<<extend>>"
I think the much-less/much-more unicode sign looks better here:
```suggestion
            return "≪extend≫"
```

2023-09-06 21:33 UTC, maximiliansoelch commented on Themis/Models/UML/UMLRelationshipType.swift
> +            return "<<include>>"
Same here:
```suggestion
            return "≪include≫"
```

2023-09-07 14:45 UTC, terlan98 commented
@maximiliansoelch Thanks for the review! I implemented your suggestion.

2023-09-07 14:46 UTC, terlan98 commented on Themis/Views/Assessment/Modeling Exercise/Diagram Renderers/Class Diagram/UMLClassDiagramRelationshipRenderer.swift
> +struct UMLClassDiagramRelationshipRenderer: UMLDiagramRenderer {
Not sure why the SwiftLint action is complaining here. Removing this rule causes a `type_body_length` error 🤷‍♂️

2023-09-07 16:07 UTC, maximiliansoelch approved these changes
Thanks for implementing the change!
Approved 👍

2023-09-07 16:09 UTC, merged