`Modeling and Text Exercises`: View example solutions
ls1intum/Themis pull request #171
Opened 2023-08-06 12:52 UTC by terlan98

This PR allows viewing example solutions for modeling and text exercises. The example solution is shown in CorrectionSidebar, below the problem statement.

2023-09-28 07:21 UTC, maximiliansoelch requested changes
Is this intended?

https://github.com/ls1intum/Themis/assets/9954674/ae8f0e13-c6c9-4c09-ba00-0701bce42650

Also, the example solution does not support skeleton loading.

2023-09-28 07:21 UTC, maximiliansoelch commented on Themis/ViewModels/Assessment/Modeling/UMLRendererViewModel.swift
> +            currentDragLocation = .init(x: diagramSize.height - 50, // 50 – default padding added by Athena
What does the padding for modeling exercises have to do with Athena?

2023-09-28 07:21 UTC, maximiliansoelch commented on Themis/Views/Assessment/CorrectionSidebar/CorrectionSidebarView.swift
> +                    if !assessmentVM.loading {
Is the second loading check required? 🤔

2023-09-28 12:58 UTC, terlan98 commented on Themis/ViewModels/Assessment/Modeling/UMLRendererViewModel.swift
> +            currentDragLocation = .init(x: diagramSize.height - 50, // 50 – default padding added by Athena
Nothing, I wanted to write Apollon 😅

2023-09-28 15:04 UTC, terlan98 commented on Themis/Views/Assessment/CorrectionSidebar/CorrectionSidebarView.swift
> +                    if !assessmentVM.loading {
Actually, the first check is unnecessary. I removed that and kept this one.

2023-09-28 15:11 UTC, terlan98 commented
Thanks for the review, @maximiliansoelch 👍 
I addressed your comments. 

Regarding the video: I think it's not an issue because if the fingers are located on different canvases during the pinch gesture, it becomes two separate drag gestures, affecting both canvases. Here's a video showing this behavior in more detail:

https://github.com/ls1intum/Themis/assets/22798314/945b5706-4d3b-4f76-ac18-d767408cd035

2023-10-02 09:58 UTC, maximiliansoelch approved these changes

2023-10-02 09:59 UTC, merged