File upload exercise support
ls1intum/Themis pull request #185
Opened 2023-09-10 15:03 UTC by terlan98

2023-10-02 10:39 UTC, maximiliansoelch requested changes
Tested locally, found some issues:

1. When opening the second file upload submission, the console shows `FileRendererViewModel.setup():29 - Setup failed`
2. After some time, I receive a "Time Out Error". The problem statements are not loaded anymore and the currently logged-in user is not assigned to a course anymore. The user needs to restart in order to proceed with any assessment.


https://github.com/ls1intum/Themis/assets/9954674/ea715051-f0e2-4a33-bbce-02bf751112d1

2023-10-02 10:39 UTC, maximiliansoelch commented on Themis/Views/Assessment/File Upload Exercise/FileUploadAssessmentView.swift
> +    }
```suggestion
        if let fileExtension = fileRendererVM.fileExtension {
           let localFileUrl = fileRendererVM.localFileURL {
              
```

2023-10-02 10:39 UTC, maximiliansoelch commented on Themis/Views/Assessment/File Upload Exercise/FileUploadAssessmentView.swift
> +                VStack { // TODO: replace with a skeleton once the skeleton PR is merged
Skeleton loading should be possible now

2023-10-02 10:39 UTC, maximiliansoelch commented on Themis/ViewModels/Assessment/File Upload/FileRendererViewModel.swift
> +              let filePath = fileUploadSubmission.filePath?.dropFirst(),
This line requires at least [artemis-ios-core-modules](https://github.com/ls1intum/artemis-ios-core-modules) version 3.4.0! 
This should be adapted in the project file.

2023-10-02 10:39 UTC, maximiliansoelch commented on Themis/Views/Assessment/File Upload Exercise/File Renderers/PDFRenderer.swift
> +        PDFRenderer(url: Bundle.main.url(forResource: "proposal", withExtension: "pdf")!)
This causes preview crashes as this file is not part of the project.

2023-10-02 11:48 UTC, terlan98 commented
Thanks for the review! 🙏 

> 1. When opening the second file upload submission, the console shows `FileRendererViewModel.setup():29 - Setup failed`

This was because the 2nd submission was missing a file URL. I made some changes to handle such cases.

> 2. After some time, I receive a "Time Out Error". The problem statements are not loaded anymore and the currently logged-in user is not assigned to a course anymore. The user needs to restart in order to proceed with any assessment.

This was because of a broken branch deployed on the staging server. Should work fine with the develop branch.

2023-10-02 12:02 UTC, maximiliansoelch requested changes

2023-10-02 12:02 UTC, maximiliansoelch commented on Themis/Views/Assessment/File Upload Exercise/FileErrorIcon.swift
> +}
iOS17 is not yet supported on the build agent where we build Themis. Therefore, we need to use the old syntax so the build succeeds.

```suggestion
struct FileErrorIcon_Previews: PreviewProvider {
     static var previews: some View {
         FileErrorIcon()
     }
}
```

2023-10-03 11:08 UTC, maximiliansoelch reviewed
@terlan98 
For image files, we may also use a different option to show the image, as the current quicklook option allows the user to annotate the image. This might let the tutor think their annotations are also displayed to the student, which they are not.
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-10-03 at 13 06 27](https://github.com/ls1intum/Themis/assets/9954674/60ba38bc-5b34-4c15-a0fc-efe4977b4c2e)

2023-10-03 11:09 UTC, maximiliansoelch approved these changes
Besides a few improvements, which can be done in a follow-up, the changes look good! Also tested them locally and they work as expected 👍

2023-10-03 11:10 UTC, merged