`Documentation`: Add user guide
ls1intum/Themis pull request #247
Opened 2023-10-24 12:57 UTC by terlan98

2023-11-12 19:16 UTC, terlan98 commented on Themis.xcodeproj/project.pbxproj
> -		6564DC022A00EFFC00CF2F89 /* XCRemoteSwiftPackageReference "artemis-ios-core-modules" */ = {
I thought maybe removing this would fix the failing bamboo build, but it didn't. No idea why it's failing 🤷‍♂️

2023-11-16 18:01 UTC, maximiliansoelch requested changes

2023-11-16 18:01 UTC, maximiliansoelch commented on docs/user/assessment-overview/assessment-overview.rst
> +
This looks a bit weird. Can you either restrict the toc depth or add normal bullet points with links to the respective pages?
<img width="545" alt="image" src="https://github.com/ls1intum/Themis/assets/9954674/d6fa543f-240e-4a6e-bc0b-210ed33c5fc4">

2023-11-16 18:01 UTC, maximiliansoelch commented on Themis.xcodeproj/project.pbxproj
> -		6564DC022A00EFFC00CF2F89 /* XCRemoteSwiftPackageReference "artemis-ios-core-modules" */ = {
I fixed it with #251. You can remove the change from this PR

2023-11-16 18:01 UTC, maximiliansoelch commented on docs/user/file-upload-assessment/file-upload-assessment.rst
> +File upload exercises do **not** support referenced feedback.
Can you wrap that in an info box?

2023-11-16 18:01 UTC, maximiliansoelch commented on docs/user/programming-assessment/images/file-tree.png
Can you add a highlight around the repository picker like you did in the other screenshots?

2023-11-16 18:01 UTC, maximiliansoelch commented on docs/user/modeling-assessment/modeling-assessment.rst
> +automatically applied.
_By default, all suggestions ..._ should be also in an info box.

2023-11-16 18:01 UTC, maximiliansoelch commented on docs/user/text-assessment/text-assessment.rst
> +is enabled, you can drag your finger over the text to highlight the specific part you are referring to.
```suggestion
is enabled, you can drag your finger or the Apple Pencil over the text to highlight the specific part you are referring to.
```

2023-11-16 18:01 UTC, maximiliansoelch commented on docs/user/text-assessment/text-assessment.rst
> +You can tap on the underlines to edit or reject suggestions. By default, all
_By default, all suggestions ..._ should be also in an info box.

2023-11-18 18:06 UTC, terlan98 commented on Themis.xcodeproj/project.pbxproj
> -		6564DC022A00EFFC00CF2F89 /* XCRemoteSwiftPackageReference "artemis-ios-core-modules" */ = {
👍 Thanks!

2023-11-20 09:33 UTC, maximiliansoelch approved these changes

2023-11-20 09:33 UTC, merged