Added long press gesture to add inline feedback
ls1intum/Themis pull request #28
Opened 2022-12-02 19:28 UTC by crustypluto19

Just to give you an idea of how the workflow will look like:

https://user-images.githubusercontent.com/24537483/205370724-11c955b2-299a-4cbd-81ec-331563ce7f92.mp4

2022-12-02 20:08 UTC, botrufus approved these changes

2022-12-02 20:10 UTC, botrufus commented
I think this is a sufficient first solution, that should satisfy both normal users and power users. In the future we could maybe think of using some apple pencil button or so...

2022-12-02 20:46 UTC, tomrudnick requested changes

2022-12-02 20:46 UTC, tomrudnick commented on Themis/Views/Assessment/CodeEditor/CodeView.swift
> +class ViewController: UIViewController, UIEditMenuInteractionDelegate {
Why do we need this delegate? It does not implement any method of this protocol and the code compiles fine without it

2022-12-02 22:13 UTC, crustypluto19 commented on Themis/Views/Assessment/CodeEditor/CodeView.swift
> +class ViewController: UIViewController, UIEditMenuInteractionDelegate {
I forgot to remove it as it was needed to add custom menu actions, it is now removed!

2022-12-02 23:35 UTC, AlexExcellence approved these changes

2022-12-03 10:41 UTC, tomrudnick approved these changes

2022-12-03 22:17 UTC, merged