Categorized list for general and inline feedback
ls1intum/Themis pull request #30
Opened 2022-12-03 23:07 UTC by crustypluto19

- Changed the list styling (now collapsible) and white background
- Add general and inline feedback accordingly

2022-12-03 23:17 UTC, AlexExcellence requested changes

2022-12-03 23:17 UTC, AlexExcellence commented on Themis/Views/Assessment/CorrectionSidebar/GeneralFeedbackCellView.swift
> +                    ForEach(assessment.feedback.feedbacks.filter { $0.type == .general }) { feedback in
AssessmentModel already contains a computed property that filters the general feedbacks. Use that one instead

2022-12-03 23:17 UTC, AlexExcellence commented on Themis/Views/Assessment/CorrectionSidebar/GeneralFeedbackCellView.swift
> +                    ForEach(assessment.feedback.feedbacks.filter { $0.type == .inline }) { feedback in
same thing like above

2022-12-03 23:29 UTC, AlexExcellence approved these changes

2022-12-04 00:40 UTC, AlexExcellence reviewed
The "+" Button for the inline feedbacks section should be removed since inline feedbacks should always include a code reference so creating them from the correction sidebar doesn't really make sense.
We could also reduce the titles of the Sections to "General" and "Inline" since the User can already see in the tabbar that he's in the feedback tab.
Personally I would also set the listRowSeperators to hidden since the items are already visually seperated by its borders.

2022-12-04 11:58 UTC, botrufus commented
Changed some things while trying around and reviewing the pr. Implemented Alex's feedback and refined some of the feedback cell views design. Take a look at it, if you don't like some changes be free to change it back or even revert the commit.

2022-12-04 12:07 UTC, botrufus approved these changes

2022-12-04 12:51 UTC, merged