Loading feedbacks from Artemis
ls1intum/Themis pull request #40
Opened 2022-12-06 18:24 UTC by botrufus

This pr enables loading the feedback that is saved in Artemis (tests and previous saved feedback) to be loaded into the assessment view. The feedback is ordered by creation date and wether it is manual or automatic feedback. Also deleting automatic feedback is prevented (except in reassessment because of Artemis api). 
Another already known bug I will look into fixing in the future: after assessment, Artemis will display the test results as if they are from the Tutor.

I will also try to clean up the code around the models in the future, as its getting really messy (thanks to Artemis API).

2022-12-08 15:29 UTC, AlexExcellence requested changes
When using the slide to delete option in the general feedback view, it's now always the last item that gets deleted.

2022-12-09 15:31 UTC, botrufus commented
> When using the slide to delete option in the general feedback view, it's now always the last item that gets deleted.
> If I see it right, the reason for that is because the delete function inside that view uses the feedbacks property which is not sorted, so we need to sort that one as well when appending feedbacks.

fixed

2022-12-09 20:40 UTC, AlexExcellence approved these changes

2022-12-10 10:36 UTC, pal03377 approved these changes
Just very minor requests

2022-12-10 10:36 UTC, pal03377 commented on Themis/Models/Assessment.swift
> +// swiftlint:disable line_length
I cannot really see a reason to disable line length here. Can't we split the very long lines into multiple ones?

2022-12-10 10:36 UTC, pal03377 commented on Themis/Models/Assessment.swift
> +// make feedback encodable to send to artemis
I feel like this comment doesn't add much information for the reader

2022-12-10 10:36 UTC, pal03377 commented on Themis/Models/Assessment.swift
> +// make feedback decodable to receive feedbacks from artemis
same here

2022-12-10 16:46 UTC, merged