UML full screen viewer
ls1intum/Themis pull request #45
Opened 2022-12-11 13:56 UTC by crustypluto19

- Full screen view
- Magnification (double tap and pinch)
- Drag up or down to dismiss view

https://user-images.githubusercontent.com/24537483/206907750-d2233e73-9405-47c0-9b0c-864ad6cbb319.mp4

To be tested on a real iPad too to find out if gestures are working properly and intuitive enough :)

2022-12-11 20:27 UTC, katjanakosic approved these changes
Approved 👍🏻

2022-12-11 22:52 UTC, pal03377 approved these changes
Some minor cleanups would be nice, but otherwise great job! At some later point we will probably want the ability to zoom arbitrarily and then stay in the zoom and pan around, which is not possible right now. This is still way better than the current state!

2022-12-11 22:52 UTC, pal03377 commented on Themis/ViewModels/Assessment/UMLViewModel.swift
> +        let halgHeight = UIScreen.main.bounds.height / 2
typo: `halfHeight`

2022-12-11 22:52 UTC, pal03377 commented on Themis/Views/Assessment/AssessmentView.swift
> +            }
It already is an `.overlay`, no need for a `ZStack`.
```suggestion
            if umlVM.showUMLFullScreen {
                UMLView()
            }
```

2022-12-11 22:52 UTC, pal03377 commented on Themis/Views/Assessment/CorrectionSidebar/ProblemStatementCellView.swift
> +                        }
Maybe this could already be in a different file, but I'm not sure to be honest

2022-12-11 22:52 UTC, pal03377 commented on Themis/Views/Assessment/UML/UMLView.swift
> +        ZStack {
At first I thought this `ZStack` might not be needed as well, but then the X button on the top right is not completely at the top, so it's fine 👍 

Edit: I see, it's also for the popup background, clever!

2022-12-11 22:52 UTC, pal03377 commented on Themis/Views/Assessment/UML/UMLView.swift
> +            , alignment: .topTrailing
This comma alignment is a bit weird
```suggestion
            }).padding(5),
            alignment: .topTrailing
```

2022-12-11 22:52 UTC, pal03377 commented on Themis/Views/Assessment/UML/UMLView.swift
> +        }).onEnded(umlVM.onEnd(value:)))
Wow, I did not know this was possible in Swift! Nice!

2022-12-12 10:56 UTC, tomrudnick reviewed
I don't see the close button in light mode:
![IMG_0FEE1ACADF2F-1](https://user-images.githubusercontent.com/16856573/207027812-05ed7abb-32f0-44e1-ac60-b9ec4160d672.jpeg)

A CPU consumption of: 74 % seems a bit high for an iPad Air displaying a picture(tested on real device)


![Screenshot 2022-12-12 at 11 52 33](https://user-images.githubusercontent.com/16856573/207027984-6f231a69-e744-45ba-a99f-a2e27fcc386f.png)

Two Purple warnings that need to be fixed:

![Screenshot 2022-12-12 at 11 45 14](https://user-images.githubusercontent.com/16856573/207028065-dfc0e248-1237-4508-9d37-eb567daaf5f6.png)

2022-12-12 10:58 UTC, tomrudnick requested changes
Purple Warnings and light mode button should be fixed at least

2022-12-12 15:19 UTC, crustypluto19 commented
> Purple Warnings and light mode button should be fixed at least

I have now fixed these issues (hopefully), could you test it locally on an iPad and check the performance metrics?

2022-12-12 16:42 UTC, tomrudnick commented
![Screenshot 2022-12-12 at 17 39 15](https://user-images.githubusercontent.com/16856573/207102813-1411b5b5-45ee-4a38-8d80-0beffbe1b3ff.png)

Well performance is even worse but the other issues seem to be fixed

2022-12-12 16:42 UTC, tomrudnick approved these changes

2022-12-13 00:19 UTC, huber-florian approved these changes
Nice!

2022-12-13 01:13 UTC, merged