implement scrollToFeedback when tapping InlineFeedback in List
ls1intum/Themis pull request #49
Opened 2022-12-12 20:46 UTC by AlexExcellence

- When tapping an item of the InlineFeedbacks Section in GeneralFeedbackCellView the related file is opened and it scrolls to the range of the feedback so it is visible on screen

https://user-images.githubusercontent.com/79016456/207150865-1efde590-2325-4b44-bfcf-29215f982a77.MOV

2022-12-12 22:17 UTC, pal03377 approved these changes
Very nice idea & simply works!

2022-12-12 23:12 UTC, botrufus requested changes
I would suggest adding a scrolling animation to make it look smoother overall

2022-12-13 01:26 UTC, crustypluto19 requested changes
Great idea that significantly improves the UX! 💯 
Maybe have the highlighted code in the middle of the screen so that the user wouldn't have to scroll up each time?

2022-12-13 17:09 UTC, AlexExcellence commented
The updated version is now animated and has the highlighted range in the center. While implementing this behaviour, I realized that our CodeView's ScrollView keeps its ScrollOffset when switching files, which leads to bugs, especially when switching to shorter files. I fixed this by always scrolling to the start of a file when opening it (In the future we could store the offsets to restore them for opened files in the tab). 
I also still need to fix some warnings related to the scrollToRange feature, so it is not ready to be merged yet.

2022-12-13 23:34 UTC, AlexExcellence commented
Apparently the contenSize is dynamic (probably because the content is lazy-loaded), which affects some calculations. Therefore, this PR only works without bugs when the file of tapped inline feedback is currently selected and all its content is loaded. Will close this for now and probably try to implement it in the new CodeEditor.

2022-12-13 23:34 UTC, closed without merging