New Code Editor (not based on Runestone)
ls1intum/Themis pull request #58
Opened 2022-12-20 14:55 UTC by pal03377

2022-12-20 18:31 UTC, AlexExcellence approved these changes

2022-12-20 18:31 UTC, AlexExcellence commented on Themis/Views/Assessment/CodeEditor/CodeView.swift
> + struct CodeViewSelect: View {
We should remove this by implementing the lasso toggle functionality. But merging is more important for now.

2022-12-21 00:00 UTC, AlexExcellence requested changes

2022-12-21 00:00 UTC, AlexExcellence commented on Themis/Views/Assessment/AssessmentView.swift
> -            }
This shouldn't have been removed!

2022-12-21 00:00 UTC, AlexExcellence commented on Themis/Views/Assessment/AssessmentView.swift
>              }
This can be removed now, since we implemented the custom feedback Action in EditMenu

2022-12-21 08:35 UTC, tomrudnick approved these changes

2022-12-22 12:40 UTC, huber-florian submitted a review, later dismissed
Please rebase/merge with current develop and afterwards every reviewer should have a look again.

2022-12-22 13:10 UTC, AlexExcellence commented
> Please rebase/merge with current develop and afterwards every reviewer should have a look again.

It is already up to date!

2022-12-22 14:08 UTC, AlexExcellence commented
Just noticed, that inline feedbacks highlights aren't deleted anymore when deleting the feedback. This is because the file property of the AssessmentFeedback is always nil, which wasn't the case before. Will fix this and after that it is ready to be merged.

2022-12-22 14:32 UTC, AlexExcellence approved these changes

2022-12-22 17:45 UTC, merged